<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>3d20a266-869e-4692-9a17-593429aa477d</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\WowsKarma.Api\WowsKarma.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
      <PackageReference Include="Nodsoft.Wargaming.Api.Common" Version="0.3.5" />
    </ItemGroup>

</Project>
